// Auto-generated by: pnpm --filter @flowos/db gen:types
// Run after applying Supabase migrations to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          org_id: string | null;
          display_name: string | null;
          avatar_url: string | null;
          tier: "free" | "pro" | "enterprise";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          org_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          tier?: "free" | "pro" | "enterprise";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          tier?: "free" | "pro" | "enterprise";
          created_at?: string;
          updated_at?: string;
        };
      };
      api_keys: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          provider: string;
          vault_secret_id: string;
          is_valid: boolean;
          last_validated_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          provider: string;
          vault_secret_id: string;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          provider?: string;
          vault_secret_id?: string;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
        };
      };
      connections: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          provider: string;
          auth_type: "oauth" | "api_key";
          vault_secret_id: string;
          scopes: string[] | null;
          metadata: Json | null;
          is_valid: boolean;
          last_validated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          provider: string;
          auth_type: "oauth" | "api_key";
          vault_secret_id: string;
          scopes?: string[] | null;
          metadata?: Json | null;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          provider?: string;
          auth_type?: "oauth" | "api_key";
          vault_secret_id?: string;
          scopes?: string[] | null;
          metadata?: Json | null;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      programs: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          description: string | null;
          schema: Json;
          schema_version: number;
          execution_mode: "autonomous" | "supervised" | "manual";
          is_active: boolean;
          conflict_policy: "queue" | "skip" | "fail";
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          description?: string | null;
          schema: Json;
          schema_version?: number;
          execution_mode?: "autonomous" | "supervised" | "manual";
          is_active?: boolean;
          conflict_policy?: "queue" | "skip" | "fail";
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          description?: string | null;
          schema?: Json;
          schema_version?: number;
          execution_mode?: "autonomous" | "supervised" | "manual";
          is_active?: boolean;
          conflict_policy?: "queue" | "skip" | "fail";
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      program_connections: {
        Row: { program_id: string; connection_id: string };
        Insert: { program_id: string; connection_id: string };
        Update: { program_id?: string; connection_id?: string };
      };
      program_versions: {
        Row: {
          id: string;
          program_id: string;
          version: number;
          schema: Json;
          change_summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          version: number;
          schema: Json;
          change_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          version?: number;
          schema?: Json;
          change_summary?: string | null;
          created_at?: string;
        };
      };
      runs: {
        Row: {
          id: string;
          program_id: string;
          triggered_by: string;
          trigger_payload: Json | null;
          status: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at: string | null;
          completed_at: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          triggered_by: string;
          trigger_payload?: Json | null;
          status?: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          triggered_by?: string;
          trigger_payload?: Json | null;
          status?: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
      };
      node_executions: {
        Row: {
          id: string;
          run_id: string;
          node_id: string;
          status:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload: Json | null;
          output_payload: Json | null;
          error_message: string | null;
          retry_count: number;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          node_id: string;
          status?:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload?: Json | null;
          output_payload?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          node_id?: string;
          status?:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload?: Json | null;
          output_payload?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      approvals: {
        Row: {
          id: string;
          node_execution_id: string;
          user_id: string;
          status: "pending" | "approved" | "rejected";
          context: Json | null;
          decision_note: string | null;
          decided_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          node_execution_id: string;
          user_id: string;
          status?: "pending" | "approved" | "rejected";
          context?: Json | null;
          decision_note?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          node_execution_id?: string;
          user_id?: string;
          status?: "pending" | "approved" | "rejected";
          context?: Json | null;
          decision_note?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
      };
      triggers: {
        Row: {
          id: string;
          program_id: string;
          type: "manual" | "cron" | "webhook" | "event" | "program";
          config: Json;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          type: "manual" | "cron" | "webhook" | "event" | "program";
          config: Json;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          type?: "manual" | "cron" | "webhook" | "event" | "program";
          config?: Json;
          is_active?: boolean;
          created_at?: string;
        };
      };
      usage: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          period_start: string;
          period_end: string;
          program_count: number;
          execution_count: number;
          connection_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          period_start: string;
          period_end: string;
          program_count?: number;
          execution_count?: number;
          connection_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          period_start?: string;
          period_end?: string;
          program_count?: number;
          execution_count?: number;
          connection_count?: number;
          created_at?: string;
        };
      };
      resource_locks: {
        Row: {
          id: string;
          resource_type: string;
          resource_id: string;
          locked_by_run_id: string | null;
          acquired_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          resource_type: string;
          resource_id: string;
          locked_by_run_id?: string | null;
          acquired_at?: string;
          expires_at: string;
        };
        Update: {
          id?: string;
          resource_type?: string;
          resource_id?: string;
          locked_by_run_id?: string | null;
          acquired_at?: string;
          expires_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
