-- FlowOS - Cost and token telemetry (per-node and per-run)

ALTER TABLE public.runs
  ADD COLUMN IF NOT EXISTS prompt_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completion_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_cost_usd NUMERIC(14, 6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS connector_api_calls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS model_call_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.node_executions
  ADD COLUMN IF NOT EXISTS prompt_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completion_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_tokens BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_cost_usd NUMERIC(14, 6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS connector_api_calls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS model_call_count INTEGER NOT NULL DEFAULT 0;
